### ISSUE TITLE
Hacer un README.md en condiciones

### ISSUE THREAD

**Issue by JuanjoSalvador** [JuanjoSalvador/jpm#1]
Hacer un README.md en condiciones, el que tengo ahora es demasiado informal. Incluir todas las funciones testeadas y funcionales.

**Comment by RafaelAybar** [comment]
JPMS
Juanjo Paquetes Muy Sanos brindará el soporte para paquetes que usted lleva años esperando, hecho en rubí.

**Comment by JuanjoSalvador** [comment]
@RafaelAybar no voy a cambiar el nombre, ¿eh? xD Las siglas si puede que pasen a ser un acrónimo recursivo.
